### ISSUE TITLE
openni2

### ISSUE THREAD

**Issue by luchen828** [yiyah/KinectV1_Driver-SensorKinect#1]
你好朋友，请问一下，在ubuntu上使用kinect2设备，只安装openni2是不可以的吗？我现在编译了openni2但是提示找不到设备。如果方便，可以给点建议吗？谢谢了

**Comment by yiyah** [comment]
你好，抱歉才看到。
只安装 openni2 是不行的，需要安装 SensorKinect 这个才是 Kinect 的驱动。

**Comment by luchen828** [comment]
哈哈，谢谢！


 
---Original---
